PreCommit:
  AuthorName:
    enabled: false
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures

CommitMsg:
  CapitalizedSubject:
    enabled: false
  EmptyMessage:
    enabled: false
