Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Rails:
  Enabled: true
